server:
  grpc:
    name: Bonfire-Lit.Service.Chat
    port: 9000
    timeout: 900s

database:
  postgres:
    dsn: host=%s user=admin password=%s dbname=bonfire_lit port=%s sslmode=disable TimeZone=Asia/Shanghai

trace:
  otel_state: enable
  sample_ration: 1.0

pyroscope:
  state: enable

project:
  mode: dev

tavily:
  URL: https://mcp.tavily.com/mcp/?tavilyApiKey=%s

agent:
  model:
    chat: "Qwen/Qwen3-235B-A22B"
    retrieval: "Qwen/Qwen3-235B-A22B"

rag:
  milvus:
    username: root
  retriever:
    topK: 5
    collectionName: newC2
  embedding:
    model: doubao-embedding-large-text-250515
    